### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ptagl** [guerinoni/qTsConverter#15]
Hi,

I cloned this project and tried to compile it from Qt Creator but got the following error:

`[ 52%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxzipreader.cpp.o
/home/user/projects/qTsConverter/3rd-party/qtxlsx/src/xlsx/xlsxzipreader.cpp:28:10: fatal error: private/qzipreader_p.h: No such file or directory
   28 | #include <private/qzipreader_p.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.`

Is there any particular requirement needed to compile?

I am using:

- Ubuntu 20.04 LTS
- Qt Creator 4.11.0
- Qt 5.12.8
- CMake 3.16.3

Thanks!

**Comment by guerinoni** [comment]
@ptagl 
Did you perform a simple `git clone` or with recursive options? (`git clone --recursive`)

**Comment by ptagl** [comment]
> @ptagl
> Did you perform a simple `git clone` or with recursive options? (`git clone --recursive`)

I used the `--recursive` flag.

**Comment by guerinoni** [comment]
I just tried on my machine and it works, also CI work on GH... Maybe I'm using Qt 5.14.2 but I don't think is the main problem! It seems you don't have that file... Can you check if correctly exists on the file system? Or maybe try with different Qt versions...

**Comment by ptagl** [comment]
> I just tried on my machine and it works, also CI work on GH... Maybe I'm using Qt 5.14.2 but I don't think is the main problem! It seems you don't have that file... Can you check if correctly exists on the file system? Or maybe try with different Qt versions...

Sorry, you're right: I found out that the package qtbase5-private-dev was missing, causing the compilation error.

After fixing that (and another couple of missing modules) I was able to compile the tool, it works perfectly.

Thanks a lot for sharing it with everyone!!!

**Comment by guerinoni** [comment]
Good to know :D
