### ISSUE TITLE
[BUG] Build instructions provided in the README doesn't work

### ISSUE THREAD

**Issue by larpon** [guerinoni/qTsConverter#20]
**Describe the bug**
> A clear and concise description of what the bug is.

The build instructions provided in the README doesn't work.

1. It seems like the repository should be checked out with the `--recursive` flag?
2. I tried following the instructions and immediately got an error: 
    ```
    CMake Error: The source directory "" does not exist.
    Specify --help for usage, or press the help button on the CMake GUI.
    ```
    I also ended up with a `build/` directory in my projects folder

**To Reproduce**
> Steps to reproduce the behavior:

1. Follow the steps in the README

**Expected behavior**
> A clear and concise description of what you expected to happen.

A working build

**Screenshots**
> If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/768942/90528035-785b6b80-e172-11ea-9113-3abbdb48de4e.png)

**Desktop (please complete the following information):**

 - OS Linux Kubuntu 18.04
 - Version: `master`

**Additional context**
> Add any other context about the problem here.

I ended up using Qt Creator which worked

**Comment by guerinoni** [comment]
Yes, confirm, sorry about that! You should clone with recursive for submodules... I will fix README in a few time
