### ISSUE TITLE
Error running compiled version on OS X 

### ISSUE THREAD

**Issue by connor-lee** [guerinoni/qTsConverter#35]
Im running OSX Big Sur 11.0.1 with Qt 5.12.2 installed, I have tried using the readme command (git clone --recursive https://github.com/guerinoni/qTsConverter.git) and I have tried downloading the code directly from the GitHub website, as well as the dependencies and placed them in their folders. Both times I got this output for install with an error for libqtcsv.a:

 sudo make install
Password:
[  1%] Automatic MOC for target qtcsv
[  1%] Built target qtcsv_autogen
[ 13%] Built target qtcsv
[ 15%] Automatic MOC for target QtXlsxWriter
[ 15%] Built target QtXlsxWriter_autogen
[ 70%] Built target QtXlsxWriter
[ 71%] Automatic MOC and UIC for target qTsConverter
[ 71%] Built target qTsConverter_autogen
[100%] Built target qTsConverter
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libqtcsv.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /usr/local/lib/libqtcsv.a(mocs_compilation.cpp.o) has no symbols
-- Up-to-date: /usr/local/./include
-- Installing: /usr/local/./include/qtcsv
-- Installing: /usr/local/./include/qtcsv/reader.h
-- Installing: /usr/local/./include/qtcsv/abstractdata.h
-- Installing: /usr/local/./include/qtcsv/stringdata.h
-- Installing: /usr/local/./include/qtcsv/writer.h
-- Installing: /usr/local/./include/qtcsv/qtcsv_global.h
-- Installing: /usr/local/./include/qtcsv/variantdata.h
-- Installing: /usr/local/share/qtcsv/cmake/qtcsvConfig.cmake
-- Installing: /usr/local/share/qtcsv/cmake/qtcsvConfig-release.cmake
-- Installing: /usr/local/lib/libQtXlsxWriter.dylib
-- Installing: /usr/local/lib/cmake/QtXlsxWriter/QtXlsxWriterConfig.cmake
-- Installing: /usr/local/include/xlsxabstractooxmlfile.h
-- Installing: /usr/local/include/xlsxabstractsheet.h
-- Installing: /usr/local/include/xlsxcell.h
-- Installing: /usr/local/include/xlsxcellformula.h
-- Installing: /usr/local/include/xlsxcellrange.h
-- Installing: /usr/local/include/xlsxcellreference.h
-- Installing: /usr/local/include/xlsxchart.h
-- Installing: /usr/local/include/xlsxchartsheet.h
-- Installing: /usr/local/include/xlsxconditionalformatting.h
-- Installing: /usr/local/include/xlsxdatavalidation.h
-- Installing: /usr/local/include/xlsxdocument.h
-- Installing: /usr/local/include/xlsxformat.h
-- Installing: /usr/local/include/xlsxglobal.h
-- Installing: /usr/local/include/xlsxrichstring.h
-- Installing: /usr/local/include/xlsxworkbook.h
-- Installing: /usr/local/include/xlsxworksheet.h
-- Installing: /usr/local/bin/qTsConverter
-- Installing: /usr/local/share/doc/qTsConverter/README.md
-- Installing: /usr/local/share/licenses/qTsConverter/LICENSE
-- Installing: /usr/local/share/applications/org.guerinoni.qTsConverter.desktop
-- Installing: /usr/local/share/icons/hicolor/512x512/apps/org.guerinoni.qTsConverter.svg
-- Installing: /usr/local/share/icons/hicolor/512x512/apps/org.guerinoni.qTsConverter.png
-- Installing: /usr/local/share/metainfo/org.guerinoni.qTsConverter.appdata.xml

Then both times I tried to run I got this:

:bin connorlee$ ./qTsConverter 
dyld: Library not loaded: @rpath/QtQuick.framework/Versions/5/QtQuick
  Referenced from: /usr/local/bin/./qTsConverter
  Reason: image not found
Abort trap: 6

Is this an error in the way I am compiling?

Thanks,
Connor

**Comment by guerinoni** [comment]
Hi @connor-lee ,
My CI runs using Qt 5.15.x but maybe this is not a real problem... Try
```
mkdir build
cd build
cmake ..
cmake --build . --parallel
```

**Comment by connor-lee** [comment]
Hey @guerinoni 

Thanks for the quick response!

I tried those commands, im still getting an issue with libqtcsv, I noticed im also getting the issue at the build step as well. See below:

mkdir build
Connors-iMac:qTsConverter connorlee$ cd build
Connors-iMac:build connorlee$ cmake ..
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: -removed-
Connors-iMac:build connorlee$ cmake --build . --parallel
Scanning dependencies of target QtXlsxWriter_autogen
Scanning dependencies of target qtcsv_autogen
[  2%] Automatic MOC for target QtXlsxWriter
[  2%] Automatic MOC for target qtcsv
[  2%] Built target qtcsv_autogen
Scanning dependencies of target qtcsv
[  4%] Building CXX object 3rd-party/qtcsv/CMakeFiles/qtcsv.dir/sources/contentiterator.cpp.o
[  5%] Building CXX object 3rd-party/qtcsv/CMakeFiles/qtcsv.dir/qtcsv_autogen/mocs_compilation.cpp.o
[  8%] Building CXX object 3rd-party/qtcsv/CMakeFiles/qtcsv.dir/sources/stringdata.cpp.o
[  8%] Building CXX object 3rd-party/qtcsv/CMakeFiles/qtcsv.dir/sources/reader.cpp.o
[  9%] Building CXX object 3rd-party/qtcsv/CMakeFiles/qtcsv.dir/sources/variantdata.cpp.o
[ 11%] Building CXX object 3rd-party/qtcsv/CMakeFiles/qtcsv.dir/sources/writer.cpp.o
[ 11%] Built target QtXlsxWriter_autogen
Scanning dependencies of target QtXlsxWriter
[ 12%] Linking CXX static library libqtcsv.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libqtcsv.a(mocs_compilation.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libqtcsv.a(mocs_compilation.cpp.o) has no symbols
[ 12%] Built target qtcsv
[ 14%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/QtXlsxWriter_autogen/mocs_compilation.cpp.o
[ 15%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxabstractsheet.cpp.o
[ 16%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxabstractooxmlfile.cpp.o
[ 18%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxcell.cpp.o
[ 21%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxcellformula.cpp.o
[ 21%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxcellrange.cpp.o
[ 22%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxcellreference.cpp.o
[ 23%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxchart.cpp.o
[ 25%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxchartsheet.cpp.o
[ 26%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxcolor.cpp.o
[ 28%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxconditionalformatting.cpp.o
[ 29%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxcontenttypes.cpp.o
[ 30%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxdatavalidation.cpp.o
[ 32%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxdocpropsapp.cpp.o
[ 35%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxdocument.cpp.o
[ 35%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxdocpropscore.cpp.o
[ 36%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxdrawing.cpp.o
[ 38%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxdrawinganchor.cpp.o
[ 39%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxformat.cpp.o
[ 40%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxmediafile.cpp.o
[ 42%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxrelationships.cpp.o
[ 43%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxrichstring.cpp.o
[ 45%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxsharedstrings.cpp.o
[ 46%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxsimpleooxmlfile.cpp.o
[ 49%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxstyles.cpp.o
[ 49%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxnumformatparser.cpp.o
[ 50%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxworksheet.cpp.o
[ 52%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxzipreader.cpp.o
[ 54%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxzipwriter.cpp.o
[ 54%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxtheme.cpp.o
[ 56%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxworkbook.cpp.o
[ 57%] Building CXX object 3rd-party/qtxlsx/CMakeFiles/QtXlsxWriter.dir/src/xlsx/xlsxutility.cpp.o
[ 59%] Linking CXX shared library libQtXlsxWriter.dylib
[ 59%] Built target QtXlsxWriter
Scanning dependencies of target internal_autogen
[ 60%] Automatic MOC and UIC for target internal
[ 60%] Built target internal_autogen
Scanning dependencies of target internal
[ 61%] Building CXX object src/internal/CMakeFiles/internal.dir/ConverterFactory.cpp.o
[ 63%] Building CXX object src/internal/CMakeFiles/internal.dir/internal_autogen/mocs_compilation.cpp.o
[ 64%] Building CXX object src/internal/CMakeFiles/internal.dir/ConverterGuiProxy.cpp.o
[ 66%] Building CXX object src/internal/CMakeFiles/internal.dir/Converter.cpp.o
[ 67%] Building CXX object src/internal/CMakeFiles/internal.dir/CsvParser.cpp.o
[ 69%] Building CXX object src/internal/CMakeFiles/internal.dir/CsvBuilder.cpp.o
[ 70%] Building CXX object src/internal/CMakeFiles/internal.dir/TsBuilder.cpp.o
[ 71%] Building CXX object src/internal/CMakeFiles/internal.dir/XlsxBuilder.cpp.o
[ 73%] Building CXX object src/internal/CMakeFiles/internal.dir/XlsxParser.cpp.o
[ 78%] Building CXX object src/internal/CMakeFiles/internal.dir/TsParser.cpp.o
[ 78%] Building CXX object src/internal/CMakeFiles/internal.dir/Parser.cpp.o
[ 78%] Building CXX object src/internal/CMakeFiles/internal.dir/Builder.cpp.o
[ 78%] Building CXX object src/internal/CMakeFiles/internal.dir/ConversionModel.cpp.o
[ 80%] Linking CXX static library libinternal.a
[ 80%] Built target internal
Scanning dependencies of target tst_ts2xlsx
Scanning dependencies of target qTsConverter_autogen
Scanning dependencies of target tst_csv2ts
Scanning dependencies of target tst_ts2csv
Scanning dependencies of target tst_xlsx2ts
[ 81%] Automatic MOC and UIC for target qTsConverter
[ 83%] Building CXX object tests/CMakeFiles/tst_csv2ts.dir/tst_csv2ts.cpp.o
[ 84%] Building CXX object tests/CMakeFiles/tst_ts2csv.dir/tst_ts2csv.cpp.o
[ 85%] Building CXX object tests/CMakeFiles/tst_xlsx2ts.dir/tst_xlsx2ts.cpp.o
[ 87%] Building CXX object tests/CMakeFiles/tst_ts2xlsx.dir/tst_ts2xlsx.cpp.o
[ 87%] Built target qTsConverter_autogen
[ 88%] Automatic RCC for qml/qml.qrc
Scanning dependencies of target qTsConverter
[ 90%] Building CXX object src/CMakeFiles/qTsConverter.dir/qTsConverter_autogen/mocs_compilation.cpp.o
[ 91%] Building CXX object src/CMakeFiles/qTsConverter.dir/main.cpp.o
[ 92%] Building CXX object src/CMakeFiles/qTsConverter.dir/qTsConverter_autogen/CCBC4FUR7J/qrc_qml.cpp.o
[ 94%] Linking CXX executable tst_ts2csv
[ 95%] Linking CXX executable tst_xlsx2ts
[ 97%] Linking CXX executable tst_csv2ts
[ 97%] Built target tst_ts2csv
[ 97%] Built target tst_xlsx2ts
[ 97%] Built target tst_csv2ts
[ 98%] Linking CXX executable tst_ts2xlsx
[ 98%] Built target tst_ts2xlsx
[100%] Linking CXX executable qTsConverter
[100%] Built target qTsConverter
Connors-iMac:build connorlee$ sudo make install
[  1%] Automatic MOC for target qtcsv
[  1%] Built target qtcsv_autogen
[ 11%] Built target qtcsv
[ 12%] Automatic MOC for target QtXlsxWriter
[ 12%] Built target QtXlsxWriter_autogen
[ 59%] Built target QtXlsxWriter
[ 60%] Automatic MOC and UIC for target internal
[ 60%] Built target internal_autogen
[ 80%] Built target internal
[ 81%] Automatic MOC and UIC for target qTsConverter
[ 81%] Built target qTsConverter_autogen
[ 88%] Built target qTsConverter
[ 91%] Built target tst_ts2xlsx
[ 94%] Built target tst_xlsx2ts
[ 97%] Built target tst_csv2ts
[100%] Built target tst_ts2csv
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/libqtcsv.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /usr/local/lib/libqtcsv.a(mocs_compilation.cpp.o) has no symbols
-- Up-to-date: /usr/local/./include
-- Up-to-date: /usr/local/./include/qtcsv
-- Up-to-date: /usr/local/./include/qtcsv/reader.h
-- Up-to-date: /usr/local/./include/qtcsv/abstractdata.h
-- Up-to-date: /usr/local/./include/qtcsv/stringdata.h
-- Up-to-date: /usr/local/./include/qtcsv/writer.h
-- Up-to-date: /usr/local/./include/qtcsv/qtcsv_global.h
-- Up-to-date: /usr/local/./include/qtcsv/variantdata.h
-- Installing: /usr/local/share/qtcsv/cmake/qtcsvConfig.cmake
-- Installing: /usr/local/share/qtcsv/cmake/qtcsvConfig-noconfig.cmake
-- Installing: /usr/local/lib/libQtXlsxWriter.dylib
-- Installing: /usr/local/lib/cmake/QtXlsxWriter/QtXlsxWriterConfig.cmake
-- Up-to-date: /usr/local/include/xlsxabstractooxmlfile.h
-- Up-to-date: /usr/local/include/xlsxabstractsheet.h
-- Up-to-date: /usr/local/include/xlsxcell.h
-- Up-to-date: /usr/local/include/xlsxcellformula.h
-- Up-to-date: /usr/local/include/xlsxcellrange.h
-- Up-to-date: /usr/local/include/xlsxcellreference.h
-- Up-to-date: /usr/local/include/xlsxchart.h
-- Up-to-date: /usr/local/include/xlsxchartsheet.h
-- Up-to-date: /usr/local/include/xlsxconditionalformatting.h
-- Up-to-date: /usr/local/include/xlsxdatavalidation.h
-- Up-to-date: /usr/local/include/xlsxdocument.h
-- Up-to-date: /usr/local/include/xlsxformat.h
-- Up-to-date: /usr/local/include/xlsxglobal.h
-- Up-to-date: /usr/local/include/xlsxrichstring.h
-- Up-to-date: /usr/local/include/xlsxworkbook.h
-- Up-to-date: /usr/local/include/xlsxworksheet.h
-- Installing: /usr/local/bin/qTsConverter
-- Up-to-date: /usr/local/share/doc/qTsConverter/README.md
-- Up-to-date: /usr/local/share/licenses/qTsConverter/LICENSE
-- Up-to-date: /usr/local/share/applications/org.guerinoni.qTsConverter.desktop
-- Up-to-date: /usr/local/share/icons/hicolor/512x512/apps/org.guerinoni.qTsConverter.svg
-- Up-to-date: /usr/local/share/icons/hicolor/512x512/apps/org.guerinoni.qTsConverter.png
-- Up-to-date: /usr/local/share/metainfo/org.guerinoni.qTsConverter.appdata.xml

Maybe a libqtcsv problem?

**Comment by guerinoni** [comment]
I don't know! I don't have any macOS machine but on GH actions works, than the problem can be also the Qt version!

**Comment by guerinoni** [comment]
@connor-lee 
Any news?

**Comment by connor-lee** [comment]
I was checking and the paths in the executable still contain @rpath instead of the paths to the correct qt frameworks. 

I found online it could be caused by installing qt before Xcode. I tried reinstalling qt to verify if that fixed the issue but qt installers were down. Im going to try again tonight and ill get back to you as soon as I can.

**Comment by connor-lee** [comment]
hey @guerinoni sorry for the slow response.

Looks like RPATH is not set properly, can be fixed by changing cmakelists.txt to code below 

(I do not fully understand the code it is not mine, modified from here: https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling) 

cmake_minimum_required(VERSION 3.10)

project(
  qTsConverter
  LANGUAGES CXX
  VERSION "4.3.4"
  DESCRIPTION
    "Tool used to convert `.ts` file of Qt translation in other format more editable using an office suite."
)

set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_FLAGS_INIT
    "-Werror"
    "-Wall"
    "-Wextra"
    "-Wpedantic"
    "-Warray-bounds"
    "-Wdouble-promotion"
    "-Weffc++"
    "-Wextra"
    "-Wimplicit-fallthrough"
    "-Winit-self"
    "-Wfloat-equal"
    "-Wformat=2"
    "-Wmissing-include-dirs"
    "-Wno-unused-const-variable"
    "-Wno-unused-function"
    "-Wnull-dereference"
    "-Wparentheses"
    "-Wpedantic"
    "-Wshift-overflow"
    "-Wshadow"
    "-Wstrict-aliasing=1"
    "-Wstrict-overflow=5"
    "-Wtautological-compare"
    "-Wuninitialized")

# use, i.e. don't skip the full RPATH for the build tree
set(CMAKE_SKIP_BUILD_RPATH FALSE)

# when building, don't use the install RPATH already
# (but later on when installing)
set(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)

set(CMAKE_INSTALL_RPATH "${CMAKE_PREFIX_PATH}/lib")

# add the automatically determined parts of the RPATH
# which point to directories outside the build tree to the install RPATH
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

# the RPATH to be used when installing, but only if it's not a system directory
list(FIND CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES "${CMAKE_PREFIX_PATH}/lib" isSystemDir)
if("${isSystemDir}" STREQUAL "-1")
    set(CMAKE_INSTALL_RPATH "${CMAKE_PREFIX_PATH}/lib")
endif("${isSystemDir}" STREQUAL "-1")


include(cmake/Sanitizers.cmake)
include(cmake/CompilerWarnings.cmake)

set(BUILD_TESTS
    OFF
    CACHE BOOL "build tests" FORCE)
set(STATIC_LIB
    ON
    CACHE BOOL "build as static lib if ON, otherwise build shared lib" FORCE)

add_subdirectory(3rd-party/qtcsv)
add_subdirectory(3rd-party/qtxlsx)
add_subdirectory(src)
enable_testing()
add_subdirectory(tests)
add_subdirectory(data)

I have it running now! will test it tomorrow

**Comment by guerinoni** [comment]
@connor-lee do you resolve your problem?
