### ISSUE TITLE
[BUG] Error opening FileDialog

### ISSUE THREAD

**Issue by itarozzi** [guerinoni/qTsConverter#40]
**Describe the bug**

When I click on "BROWSE" button nothing appear and in the terminal I can see the following error message:

`
ERROR: No native FileDialog implementation available.
Qt Labs Platform requires Qt Widgets on this setup.
Add 'QT += widgets' to .pro and create QApplication in main().
`

**To Reproduce**
1. Execute the application on linux terminal
2. Click on 'BROWSE' button
3. See error on console 

**Expected behavior**
Open the DialogFile to select the file to convert

**Desktop (please complete the following information):**
 - OS : Linux Manjaro
 

**Additional context**
When I execute the application, before to press the button, I can see the following message:

`
qt.qpa.xcb: QXcbConnection: XCB error: 5 (BadAtom), sequence: 474, resource id: 0, major code: 20 (GetProperty), minor code: 0
`

**Comment by guerinoni** [comment]
@itarozzi 
Hi, I think I solved it, can you send me feedback with this branch `https://github.com/guerinoni/qTsConverter/tree/fix-manjaro-file-dialog`?

**Comment by itarozzi** [comment]
Amazing! the new branch works without issues.

Grazie mille!!!

**Comment by guerinoni** [comment]
Thank you! I will merge it :D
