### ISSUE TITLE
[BUG] xlsx->ts with japanese produces word doubling

### ISSUE THREAD

**Issue by joernweissenborn** [guerinoni/qTsConverter#43]
**Describe the bug**

I do not speak Japanese, but I discovered the following bug when using qTsConverter with Japanese translation. So there are three ways to write Japanese letters, Hiragana, Katakana, Kanji.

My client used  Kanji in the Excel sheet, but in the resulting ts, the word was written both as Kanji and Katakana. 

Example:

English: General
Translation in xlsx: 全般設定/装置情報
Output in ts:  全般設定/装置情報ゼンパンセッテイソウ

**To Reproduce**

Create a ts with the word "General". Create xlsx, translate as above, convert to ts. 

**Expected behavior**
The translation string in the ts should be the same as in the xlsx.

**Version**
4.3.4 git 519dfbd

**Comment by guerinoni** [comment]
I can watch this problem :)

**Comment by guerinoni** [comment]
Hi @joernweissenborn I can't reproduce this, I tried to create a XLSX with `全般設定/装置情報` and converting to TS and results seems ok

**Comment by joernweissenborn** [comment]
@guerinoni Thanks for looking into it. I know suspect a weird transformation bug happened (maybe in office360) during the transport of the file to me which didn't show up in LibreOffice. I also had other weird encoding issues with ts files (they were somehow decoded into the Japanese ASCII instead UTF-8).

So I guess one has simply has to be careful in file exchange with Japanese. I close it because it clearly is not related to qTsConverter.

Thanks a lot by the way for creating this project, it saves me a lot of hassle!
