### ISSUE TITLE
[Feature request] Command Line Interface

### ISSUE THREAD

**Issue by joernweissenborn** [guerinoni/qTsConverter#53]
I think a commandline in interface would be very handy to automate conversion. E.g. I would like to integrate qStrConverter into my CI in a workflow where I commit in an xlsx file and have it generate the ts.

This of course does not work with a GUI so a pure command line interface is needed.

an example usage would be:

```shell
qTsConverterCli xlsx-to-ts --in=myfile.xlsx --out=myfile.ts
```

**Comment by joernweissenborn** [comment]
So I looked at the tests to get an Idea about the internals of qTsConverter and I think this should be fairly straightforward to implement [with Qt included Batteries](https://doc.qt.io/qt-5/qcommandlineparser.html). 

I could make a PR for this, but I don't know if you guys maybe have your own ideas about how it should work. Just let me know, but for my workflow it would enough improvement to invest some work on my side ;)

**Comment by guerinoni** [comment]
Thank you for the suggestion :), CLI version can be very handy, I will work on the first draft of implementation!
After this you can add more feature or arguments in easy and fast way :)

**Comment by guerinoni** [comment]
@joernweissenborn first simple implementation done in `master`... Let me know if can be a good start :)

**Comment by joernweissenborn** [comment]
I will try it out asap. Maybe you can add a small usage to your readme?

Otherwise thanks for the effort!

**Comment by joernweissenborn** [comment]
One question: how to you handle exceptions? For usage in CLI one needs a non zero exit code if problems are encountered.

**Comment by guerinoni** [comment]
I will take care of that

**Comment by joernweissenborn** [comment]
So I tried out the interface now, works fine :+1: 

Haven't tested exceptions so far.

**Comment by guerinoni** [comment]
I close this issue... If you have other specific requests feel free to open other requests :)
