### ISSUE TITLE
[BUG] Error trying to run qTsConverter

### ISSUE THREAD

**Issue by knochenhans** [guerinoni/qTsConverter#57]
**Describe the bug**
> Hi, trying to run qTsConverter gives me the following error message:
```
QQmlApplicationEngine failed to load component
qrc:/main.qml:4:1: plugin cannot be loaded for module "QtQuick.Controls": Cannot protect module QtQuick.Controls 2 as it was never registered
```

**To Reproduce**
1. Start qTsConverter

**Expected behavior**
> normally running program :)

**Desktop (please complete the following information):**
 - Arch Linux
 - qTsConverter version: 4.3.4 (problem also occurs with current GIT version)
 - QT version: 5.15.2

**Comment by guerinoni** [comment]
This is probably a wrong config of Qt in your system... I will try on an arch machine :)

**Comment by knochenhans** [comment]
Thanks for investigating :) this is a freshly set up system, I didn’t do anything Qt-specific, so maybe it’s related to recent Qt package updates (I used qTsConverter successfully before on another Arch system a few months back).
