### ISSUE TITLE
Text cut inside conversion combo-box

### ISSUE THREAD

**Issue by AndreaRicchi** [guerinoni/qTsConverter#9]
With the latest UI changes, the text inside the conversion combo-box is longer than the combo itself.

![Screenshot from 2020-03-05 19-07-10](https://user-images.githubusercontent.com/17642033/76011428-da058180-5f14-11ea-88a1-7ebd65413c7e.png)

**Comment by kelteseth** [comment]
Interesting. On windows this looks normal:
![image](https://user-images.githubusercontent.com/1071536/76017947-c01d6c00-5f1f-11ea-9f0e-23c608722818.png)

An easy fix:
![image](https://user-images.githubusercontent.com/1071536/76018188-20aca900-5f20-11ea-9a4c-0e9f64cbae49.png)



``` qml
RowLayout {
            spacing: 20
            ComboBox {
                id: comboType
                Layout.preferredWidth: 200
                model: ["TS => CSV", "CSV => TS", "TS => XLSX", "XLSX => TS"]
            }
```

**Comment by AndreaRicchi** [comment]
I think the issue is related to the fact that I don't have the _Roboto_ font installed. I think is better to embed it in the application instead of applying a simple hotfix.

**Comment by kelteseth** [comment]
Ok but I only can add the fonts when we move the qml.qrc file in the root dir. For some reason qrc does not like ../paths

``` cpp
    // Returns -1 aka faild
    qDebug() << QFontDatabase::addApplicationFont(":/../assets/fonts/Roboto-Light.ttf");
    qDebug() << QFontDatabase::addApplicationFont(":/../assets/fonts/Roboto-Regular.ttf");

   // Returns 0 1
    qDebug() << QFontDatabase::addApplicationFont(":/assets/fonts/Roboto-Light.ttf");
    qDebug() << QFontDatabase::addApplicationFont(":/assets/fonts/Roboto-Regular.ttf");
```

**Comment by kelteseth** [comment]
@AndreaRicchi  can you test my changes at https://github.com/kelteseth/qt-ts-csv ?

**Comment by AndreaRicchi** [comment]
I've just tested it and it works properly. The fonts are loaded correctly and the combo box text is not cut.

**Comment by kelteseth** [comment]
Ok thanks!
